name: Move linked issues to Ready for Review

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event and PR
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "PR: ${{ github.event.number }}"
          echo "Issues: ${{ github.event.pull_request.issue }}"
          echo "Issues: ${{ github.event.issue.number }}"
          echo "PR: ${{ github.event.pull_request }}"
          echo "PR: ${{ github.event.pull_request.head }}"
      - name: Get Linked Issues
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.list({
              filter: all,
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100
            });
            const linkedIssues = issues.filter(issue => issue.body.includes('Linked issues:'));
            const linkedIssueNumbers = linkedIssues[0].body.match(/#(\d+)/g).map(issue => issue.replace('#', ''));
            console.log(linkedIssueNumbers);
            core.setOutput('linkedIssueNumbers', linkedIssueNumbers.join(','));
        id: get_linked_issues
      - name: Print linked issues
        run: |
          echo "Linked issues: ${{ steps.get_linked_issues.outputs.linkedIssueNumbers }}"

      # - name: Move Linked Issues to Ready for Review
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const linkedIssueNumbers = core.getInput('linkedIssueNumbers').split(',');
      #       for (const issueNumber of linkedIssueNumbers) {
      #         await github.issues.update({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           issue_number: issueNumber,
      #           state: 'open',
      #           labels: ['Ready for Review']
      #         });
      #       }
      #   id: move_linked_issues
      #   if: ${{ github.event.pull_request.merged == true }}
      #   with:
      #     linkedIssueNumbers: ${{ steps.get_linked_issues.outputs.linkedIssueNumbers }}
